apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
  namespace: app
data:
  ELASTIC_INDEX: "purchases"
  ELASTIC_URL: "elasticsearch-master.elastic:9200"
  KAFKA_CLIENT_ID: "ice-cream-purchases"
  KAFKA_CONSUMER_TIMEOUT_MS: "10000"
  KAFKA_CONSUMER_GROUP: "ice-cream-purchases-group"
  KAFKA_TOPIC: "purchase-events"
  KAFKA_URL: "cluster-kafka-bootstrap.kafka:9092"
