apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: web-server
        image: ademirovic/do-k8s-challenge:0.2
        imagePullPolicy: Always
        command: ['/usr/local/bin/uvicorn']
        args:
          [
            '--host',
            '0.0.0.0',
            '--port',
            '8000',
            'main:app',
            '--app-dir',
            'app'
          ]
        readinessProbe:
          httpGet:
            port: 8000
            path: /healthz
            httpHeaders:
              - name: Host
                value: $HTTP_HOST
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 2
        livenessProbe:
          httpGet:
            port: 8000
            path: /healthz
            httpHeaders:
              - name: Host
                value: $HTTP_HOST
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 2
        resources:
          requests:
            memory: 128Mi
            cpu: 150m
          limits:
            memory: 500Mi
            cpu: 500m
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: app-config-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ademirovic/do-k8s-challenge:0.2
        imagePullPolicy: Always
        command: ['/usr/local/bin/python']
        args:
          [
            'app/consumer.py',
          ]
        resources:
          requests:
            memory: 128Mi
            cpu: 150m
          limits:
            memory: 500Mi
            cpu: 500m
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: app-config-map
