apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: purchase-events
  labels:
    strimzi.io/cluster: cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
